spring:
  application:
    name: spring-server

  datasource:
    url: jdbc:postgresql://127.0.0.1/spring-server_db

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: test
      password: test

app:
  secret: 933ed358-a401-4e1e-b1e7-1d655b1ed3d7
  expirationDate: 900000

server:
  port: 8080
